require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'NativeApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'NativeAppTests' do
    inherit! :complete
    # Pods for testing
  end

  use_flipper!({ 'Flipper' => '0.76.0' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end

